name: Lint, format & type check
on:
  pull_request: {}
jobs:
  prettier:
    name: Lint, format & type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Enable Corepack
        run: corepack enable
      - name: Yarn cache
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: "yarn"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "yarn install --immutable"
      - name: Prettier
        run: "yarn run prettier:check"
      - name: i18n
        run: "yarn run i18n:check"
      - name: ESLint
        run: "yarn run lint:eslint"
      - name: Type check
        run: "yarn run lint:types"
      - name: Dead code analysis
        run: "yarn run lint:knip"
